### ISSUE TITLE
vim package manager?

### ISSUE THREAD

**Issue by kirkins** [deathbeam/dotfiles#3]
Sorry to bug you again. 

Does this use a vim package manager? I've been using vim for a month or two and this is the first time I've used plugins. Trying to figure out if I should be following the instructions to uninstall one with a package manager or manually.

**Comment by deathbeam** [comment]
I am not using any vim package manager here. I was using Plug and Vundle before, but now I am using jus [pathogen](https://github.com/tpope/vim-pathogen) to manage `runtimepath` and loading all plugins as [git submodules](https://github.com/deathbeam/awesomedotrc/tree/master/lib/vim). It is alot better methon than using plugin managers, because then you have full control over updating and removing them without relying on package manager.

**Comment by kirkins** [comment]
Gotcha, do you think removing the submodule and running re-base will be enough to uninstall one?

**Comment by deathbeam** [comment]
Yes, that is beauty of using only submodules for plugins. Also, if you want to just disable it, you can add name of the plugin to [pathogen blacklist](https://github.com/deathbeam/awesomedotrc/blob/master/dotfiles/vimrc#L11)

**Comment by kirkins** [comment]
Like this:

`let g:pathogen_blacklist=['vim-pathogen','hardmode']`

I know, I'm weak but I'll re-enable it later haha.

**Comment by kirkins** [comment]
No it seems I'm doing it wrong

**Comment by deathbeam** [comment]
Yep, that should do it. What do you mean that you are doing it wrong? And don't worry, we were all there, the arrow key hell, haha. I started using `hardmode` plugin just to force myself to stop using the arrow keys and pageup, pagedown and learn to use hjkl properly, and now I am even trying to not use hjkl and use only motions instead (but I am not brave enough to fully disable hjkl yet).
